using System.Collections.Generic;

namespace JacutemAAI2.WPF.Images.ImagesMapPath
{
    public class SpritesModoTile: FilePaths
    {
        public SpritesModoTile()
        {
            Type = "Sprites Modo Tile";
            List = new Dictionary<string, string>()
            {
                ["0043_save.ncgr"] = @"__Binarios\com_save\0043_save.ncgr,__Binarios\com_save\0044_save.nclr,__Binarios\com_save\0042_save.ncer,__Imagens\com_save\",
                ["0002_save_local.ncgr"] = @"__Binarios\jpn_save_local\0002_save_local.ncgr,__Binarios\jpn_save_local\0003_save_local.nclr,__Binarios\jpn_save_local\0001_save_local.ncer,__Imagens\jpn_save_local\",
                ["0006_save_local.ncgr"] = @"__Binarios\jpn_save_local\0006_save_local.ncgr,__Binarios\jpn_save_local\0007_save_local.nclr,__Binarios\jpn_save_local\0005_save_local.ncer,__Imagens\jpn_save_local\",
                ["0005_title_local.ncgr"] = @"__Binarios\jpn_title_local\0005_title_local.ncgr,__Binarios\jpn_title_local\0006_title_local.nclr,__Binarios\jpn_title_local\0004_title_local.ncer,__Imagens\jpn_title_local\",
                ["0010_opening.ncgr"] = @"__Binarios\com_opening\0010_opening.ncgr,__Binarios\com_opening\0011_opening.nclr,__Binarios\com_opening\0009_opening.ncer,__Imagens\com_opening\",
                ["0014_opening.ncgr"] = @"__Binarios\com_opening\0014_opening.ncgr,__Binarios\com_opening\0015_opening.nclr,__Binarios\com_opening\0013_opening.ncer,__Imagens\com_opening\",
                ["0000_opening_local.ncgr"] = @"__Binarios\jpn_opening_local\0000_opening_local.ncgr,__Binarios\jpn_opening_local\0001_opening_local.nclr,__Binarios\jpn_opening_local\0002_opening_local.ncer,__Imagens\jpn_opening_local\",
                ["0007_logicmat.ncgr"] = @"__Binarios\com_logicmat\0007_logicmat.ncgr,__Binarios\com_logicmat\0008_logicmat.nclr,__Binarios\com_logicmat\0006_logicmat.ncer,__Imagens\com_logicmat\",
                ["0011_logicmat.ncgr"] = @"__Binarios\com_logicmat\0011_logicmat.ncgr,__Binarios\com_logicmat\0012_logicmat.nclr,__Binarios\com_logicmat\0010_logicmat.ncer,__Imagens\com_logicmat\",
                ["0015_logicmat.ncgr"] = @"__Binarios\com_logicmat\0015_logicmat.ncgr,__Binarios\com_logicmat\0012_logicmat.nclr,__Binarios\com_logicmat\0014_logicmat.ncer,__Imagens\com_logicmat\",
                ["0077_idcom.ncgr"] = @"__Binarios\com_idcom\0077_idcom.ncgr,__Binarios\com_idcom\0078_idcom.nclr,__Binarios\com_idcom\0076_idcom.ncer,__Imagens\com_idcom\",
                ["0081_idcom.ncgr"] = @"__Binarios\com_idcom\0081_idcom.ncgr,__Binarios\com_idcom\0078_idcom.nclr,__Binarios\com_idcom\0080_idcom.ncer,__Imagens\com_idcom\",
                ["0084_idcom.ncgr"] = @"__Binarios\com_idcom\0084_idcom.ncgr,__Binarios\com_idcom\0085_idcom.nclr,__Binarios\com_idcom\0083_idcom.ncer,__Imagens\com_idcom\",
                ["0990_idcom.ncgr"] = @"__Binarios\com_idcom\0990_idcom.ncgr,__Binarios\com_idcom\0984_idcom.nclr,__Binarios\com_idcom\0989_idcom.ncer,__Imagens\com_idcom\",
                ["0994_idcom.ncgr"] = @"__Binarios\com_idcom\0994_idcom.ncgr,__Binarios\com_idcom\0998_idcom.nclr,__Binarios\com_idcom\0993_idcom.ncer,__Imagens\com_idcom\",
                ["0997_idcom.ncgr"] = @"__Binarios\com_idcom\0997_idcom.ncgr,__Binarios\com_idcom\0998_idcom.nclr,__Binarios\com_idcom\0996_idcom.ncer,__Imagens\com_idcom\",
                ["1001_idcom.ncgr"] = @"__Binarios\com_idcom\1001_idcom.ncgr,__Binarios\com_idcom\1002_idcom.nclr,__Binarios\com_idcom\1000_idcom.ncer,__Imagens\com_idcom\",
                ["1005_idcom.ncgr"] = @"__Binarios\com_idcom\1005_idcom.ncgr,__Binarios\com_idcom\1006_idcom.nclr,__Binarios\com_idcom\1004_idcom.ncer,__Imagens\com_idcom\",
                ["1009_idcom.ncgr"] = @"__Binarios\com_idcom\1009_idcom.ncgr,__Binarios\com_idcom\1010_idcom.nclr,__Binarios\com_idcom\1008_idcom.ncer,__Imagens\com_idcom\",
                ["1013_idcom.ncgr"] = @"__Binarios\com_idcom\1013_idcom.ncgr,__Binarios\com_idcom\1014_idcom.nclr,__Binarios\com_idcom\1012_idcom.ncer,__Imagens\com_idcom\",
                ["1017_idcom.ncgr"] = @"__Binarios\com_idcom\1017_idcom.ncgr,__Binarios\com_idcom\1018_idcom.nclr,__Binarios\com_idcom\1016_idcom.ncer,__Imagens\com_idcom\",
                ["1021_idcom.ncgr"] = @"__Binarios\com_idcom\1021_idcom.ncgr,__Binarios\com_idcom\1022_idcom.nclr,__Binarios\com_idcom\1020_idcom.ncer,__Imagens\com_idcom\",
                ["1025_idcom.ncgr"] = @"__Binarios\com_idcom\1025_idcom.ncgr,__Binarios\com_idcom\1026_idcom.nclr,__Binarios\com_idcom\1024_idcom.ncer,__Imagens\com_idcom\",
                ["1029_idcom.ncgr"] = @"__Binarios\com_idcom\1029_idcom.ncgr,__Binarios\com_idcom\1030_idcom.nclr,__Binarios\com_idcom\1028_idcom.ncer,__Imagens\com_idcom\",
                ["1033_idcom.ncgr"] = @"__Binarios\com_idcom\1033_idcom.ncgr,__Binarios\com_idcom\1034_idcom.nclr,__Binarios\com_idcom\1032_idcom.ncer,__Imagens\com_idcom\",
                ["1037_idcom.ncgr"] = @"__Binarios\com_idcom\1037_idcom.ncgr,__Binarios\com_idcom\1038_idcom.nclr,__Binarios\com_idcom\1036_idcom.ncer,__Imagens\com_idcom\",
                ["1041_idcom.ncgr"] = @"__Binarios\com_idcom\1041_idcom.ncgr,__Binarios\com_idcom\1042_idcom.nclr,__Binarios\com_idcom\1040_idcom.ncer,__Imagens\com_idcom\",
                ["1055_idcom.ncgr"] = @"__Binarios\com_idcom\1055_idcom.ncgr,__Binarios\com_idcom\1056_idcom.nclr,__Binarios\com_idcom\1054_idcom.ncer,__Imagens\com_idcom\",
                ["1059_idcom.ncgr"] = @"__Binarios\com_idcom\1059_idcom.ncgr,__Binarios\com_idcom\1060_idcom.nclr,__Binarios\com_idcom\1058_idcom.ncer,__Imagens\com_idcom\",
                ["1059_idcom.ncgr"] = @"__Binarios\com_idcom\1059_idcom.ncgr,__Binarios\com_idcom\1061_idcom.nclr,__Binarios\com_idcom\1058_idcom.ncer,__Imagens\com_idcom\",
                ["1059_idcom.ncgr"] = @"__Binarios\com_idcom\1059_idcom.ncgr,__Binarios\com_idcom\1062_idcom.nclr,__Binarios\com_idcom\1058_idcom.ncer,__Imagens\com_idcom\",
                ["1059_idcom.ncgr"] = @"__Binarios\com_idcom\1059_idcom.ncgr,__Binarios\com_idcom\1063_idcom.nclr,__Binarios\com_idcom\1058_idcom.ncer,__Imagens\com_idcom\",
                ["0093_idcom.ncgr"] = @"__Binarios\com_idcom\0093_idcom.ncgr,__Binarios\com_idcom\0090_idcom.nclr,__Binarios\com_idcom\0092_idcom.ncer,__Imagens\com_idcom\",
                ["0097_idcom.ncgr"] = @"__Binarios\com_idcom\0097_idcom.ncgr,__Binarios\com_idcom\0094_idcom.nclr,__Binarios\com_idcom\0096_idcom.ncer,__Imagens\com_idcom\",
                ["0987_idcom.ncgr"] = @"__Binarios\com_idcom\0987_idcom.ncgr,__Binarios\com_idcom\0984_idcom.nclr,__Binarios\com_idcom\0986_idcom.ncer,__Imagens\com_idcom\",
                ["0673_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0673_idlocal.ncgr,__Binarios\jpn_idlocal\0674_idlocal.nclr,__Binarios\jpn_idlocal\0672_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0273_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0273_idlocal.ncgr,__Binarios\jpn_idlocal\0274_idlocal.nclr,__Binarios\jpn_idlocal\0272_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0020_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0020_idlocal.ncgr,__Binarios\jpn_idlocal\0017_idlocal.nclr,__Binarios\jpn_idlocal\0019_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0278_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0278_idlocal.ncgr,__Binarios\jpn_idlocal\0275_idlocal.nclr,__Binarios\jpn_idlocal\0277_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0282_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0282_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0281_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0285_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0285_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0284_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0288_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0288_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0287_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0291_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0291_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0290_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0294_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0294_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0293_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0297_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0297_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0296_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0300_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0300_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0299_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0303_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0303_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0302_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0306_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0306_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0305_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0309_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0309_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0308_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0312_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0312_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0311_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0315_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0315_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0314_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0318_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0318_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0317_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0321_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0321_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0320_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0324_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0324_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0323_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0327_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0327_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0326_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0328_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0328_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0330_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0331_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0331_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0333_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0334_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0334_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0336_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0337_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0337_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0339_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0340_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0340_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0342_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0343_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0343_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0345_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0346_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0346_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0348_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0349_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0349_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0351_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0352_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0352_idlocal.ncgr,__Binarios\jpn_idlocal\0279_idlocal.nclr,__Binarios\jpn_idlocal\0354_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0357_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0357_idlocal.ncgr,__Binarios\jpn_idlocal\0358_idlocal.nclr,__Binarios\jpn_idlocal\0356_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0361_idlocal.ncgr"] = @"__Binarios\jpn_idlocal\0361_idlocal.ncgr,__Binarios\jpn_idlocal\0362_idlocal.nclr,__Binarios\jpn_idlocal\0360_idlocal.ncer,__Imagens\jpn_idlocal\",
                ["0002_opening.ncgr"] = @"__Binarios\com_opening\0002_opening.ncgr,__Binarios\com_opening\0003_opening.nclr,__Binarios\com_opening\0001_opening.ncer,__Imagens\com_opening\",
                ["0006_opening.ncgr"] = @"__Binarios\com_opening\0006_opening.ncgr,__Binarios\com_opening\0007_opening.nclr,__Binarios\com_opening\0005_opening.ncer,__Imagens\com_opening\",
                ["0018_opening.ncgr"] = @"__Binarios\com_opening\0018_opening.ncgr,__Binarios\com_opening\0019_opening.nclr,__Binarios\com_opening\0017_opening.ncer,__Imagens\com_opening\",
                ["0022_opening.ncgr"] = @"__Binarios\com_opening\0022_opening.ncgr,__Binarios\com_opening\0023_opening.nclr,__Binarios\com_opening\0021_opening.ncer,__Imagens\com_opening\",
                ["0026_opening.ncgr"] = @"__Binarios\com_opening\0026_opening.ncgr,__Binarios\com_opening\0027_opening.nclr,__Binarios\com_opening\0025_opening.ncer,__Imagens\com_opening\",
                ["0013_opening_local.ncgr"] = @"__Binarios\jpn_opening_local\0013_opening_local.ncgr,__Binarios\jpn_opening_local\0014_opening_local.nclr,__Binarios\jpn_opening_local\0012_opening_local.ncer,__Imagens\jpn_opening_local\",
                ["0002_idcom.ncgr"] = @"__Binarios\com_idcom\0002_idcom.ncgr,__Binarios\com_idcom\0003_idcom.nclr,__Binarios\com_idcom\0001_idcom.ncer,__Imagens\com_idcom\",
                ["0001_logicin.ncgr"] = @"__Binarios\com_logicin\0001_logicin.ncgr,__Binarios\com_logicin\0000_logicin.nclr,__Binarios\com_logicin\0002_logicin.ncer,__Imagens\com_logicin\",
                ["0005_logicin.ncgr"] = @"__Binarios\com_logicin\0005_logicin.ncgr,__Binarios\com_logicin\0004_logicin.nclr,__Binarios\com_logicin\0006_logicin.ncer,__Imagens\com_logicin\",
                ["0002_mapobj.ncgr"] = @"__Binarios\com_mapobj\0002_mapobj.ncgr,__Binarios\com_mapobj\0003_mapobj.nclr,__Binarios\com_mapobj\0000_mapobj.ncer,__Imagens\com_mapobj\",
                ["0010_mapobj.ncgr"] = @"__Binarios\com_mapobj\0010_mapobj.ncgr,__Binarios\com_mapobj\0011_mapobj.nclr,__Binarios\com_mapobj\0008_mapobj.ncer,__Imagens\com_mapobj\",
                ["0014_mapobj.ncgr"] = @"__Binarios\com_mapobj\0014_mapobj.ncgr,__Binarios\com_mapobj\0015_mapobj.nclr,__Binarios\com_mapobj\0012_mapobj.ncer,__Imagens\com_mapobj\",
                ["0018_mapobj.ncgr"] = @"__Binarios\com_mapobj\0018_mapobj.ncgr,__Binarios\com_mapobj\0019_mapobj.nclr,__Binarios\com_mapobj\0016_mapobj.ncer,__Imagens\com_mapobj\",
                ["0022_mapobj.ncgr"] = @"__Binarios\com_mapobj\0022_mapobj.ncgr,__Binarios\com_mapobj\0023_mapobj.nclr,__Binarios\com_mapobj\0020_mapobj.ncer,__Imagens\com_mapobj\",
                ["0026_mapobj.ncgr"] = @"__Binarios\com_mapobj\0026_mapobj.ncgr,__Binarios\com_mapobj\0027_mapobj.nclr,__Binarios\com_mapobj\0024_mapobj.ncer,__Imagens\com_mapobj\",
                ["0030_mapobj.ncgr"] = @"__Binarios\com_mapobj\0030_mapobj.ncgr,__Binarios\com_mapobj\0031_mapobj.nclr,__Binarios\com_mapobj\0028_mapobj.ncer,__Imagens\com_mapobj\",
                ["0034_mapobj.ncgr"] = @"__Binarios\com_mapobj\0034_mapobj.ncgr,__Binarios\com_mapobj\0035_mapobj.nclr,__Binarios\com_mapobj\0032_mapobj.ncer,__Imagens\com_mapobj\",
                ["0038_mapobj.ncgr"] = @"__Binarios\com_mapobj\0038_mapobj.ncgr,__Binarios\com_mapobj\0039_mapobj.nclr,__Binarios\com_mapobj\0036_mapobj.ncer,__Imagens\com_mapobj\",
                ["0042_mapobj.ncgr"] = @"__Binarios\com_mapobj\0042_mapobj.ncgr,__Binarios\com_mapobj\0043_mapobj.nclr,__Binarios\com_mapobj\0040_mapobj.ncer,__Imagens\com_mapobj\",
                ["0046_mapobj.ncgr"] = @"__Binarios\com_mapobj\0046_mapobj.ncgr,__Binarios\com_mapobj\0047_mapobj.nclr,__Binarios\com_mapobj\0044_mapobj.ncer,__Imagens\com_mapobj\",
                ["0050_mapobj.ncgr"] = @"__Binarios\com_mapobj\0050_mapobj.ncgr,__Binarios\com_mapobj\0051_mapobj.nclr,__Binarios\com_mapobj\0048_mapobj.ncer,__Imagens\com_mapobj\",
                ["0054_mapobj.ncgr"] = @"__Binarios\com_mapobj\0054_mapobj.ncgr,__Binarios\com_mapobj\0055_mapobj.nclr,__Binarios\com_mapobj\0052_mapobj.ncer,__Imagens\com_mapobj\",
                ["0058_mapobj.ncgr"] = @"__Binarios\com_mapobj\0058_mapobj.ncgr,__Binarios\com_mapobj\0059_mapobj.nclr,__Binarios\com_mapobj\0056_mapobj.ncer,__Imagens\com_mapobj\",
                ["0062_mapobj.ncgr"] = @"__Binarios\com_mapobj\0062_mapobj.ncgr,__Binarios\com_mapobj\0063_mapobj.nclr,__Binarios\com_mapobj\0060_mapobj.ncer,__Imagens\com_mapobj\",
                ["0066_mapobj.ncgr"] = @"__Binarios\com_mapobj\0066_mapobj.ncgr,__Binarios\com_mapobj\0067_mapobj.nclr,__Binarios\com_mapobj\0064_mapobj.ncer,__Imagens\com_mapobj\",
                ["0070_mapobj.ncgr"] = @"__Binarios\com_mapobj\0070_mapobj.ncgr,__Binarios\com_mapobj\0071_mapobj.nclr,__Binarios\com_mapobj\0068_mapobj.ncer,__Imagens\com_mapobj\",
                ["0074_mapobj.ncgr"] = @"__Binarios\com_mapobj\0074_mapobj.ncgr,__Binarios\com_mapobj\0075_mapobj.nclr,__Binarios\com_mapobj\0072_mapobj.ncer,__Imagens\com_mapobj\",
                ["0078_mapobj.ncgr"] = @"__Binarios\com_mapobj\0078_mapobj.ncgr,__Binarios\com_mapobj\0079_mapobj.nclr,__Binarios\com_mapobj\0076_mapobj.ncer,__Imagens\com_mapobj\",
                ["0082_mapobj.ncgr"] = @"__Binarios\com_mapobj\0082_mapobj.ncgr,__Binarios\com_mapobj\0083_mapobj.nclr,__Binarios\com_mapobj\0080_mapobj.ncer,__Imagens\com_mapobj\",
                ["0086_mapobj.ncgr"] = @"__Binarios\com_mapobj\0086_mapobj.ncgr,__Binarios\com_mapobj\0087_mapobj.nclr,__Binarios\com_mapobj\0084_mapobj.ncer,__Imagens\com_mapobj\",
                ["0090_mapobj.ncgr"] = @"__Binarios\com_mapobj\0090_mapobj.ncgr,__Binarios\com_mapobj\0091_mapobj.nclr,__Binarios\com_mapobj\0088_mapobj.ncer,__Imagens\com_mapobj\",
                ["0094_mapobj.ncgr"] = @"__Binarios\com_mapobj\0094_mapobj.ncgr,__Binarios\com_mapobj\0095_mapobj.nclr,__Binarios\com_mapobj\0092_mapobj.ncer,__Imagens\com_mapobj\",
                ["0098_mapobj.ncgr"] = @"__Binarios\com_mapobj\0098_mapobj.ncgr,__Binarios\com_mapobj\0099_mapobj.nclr,__Binarios\com_mapobj\0096_mapobj.ncer,__Imagens\com_mapobj\",
                ["0102_mapobj.ncgr"] = @"__Binarios\com_mapobj\0102_mapobj.ncgr,__Binarios\com_mapobj\0103_mapobj.nclr,__Binarios\com_mapobj\0100_mapobj.ncer,__Imagens\com_mapobj\",
                ["0106_mapobj.ncgr"] = @"__Binarios\com_mapobj\0106_mapobj.ncgr,__Binarios\com_mapobj\0107_mapobj.nclr,__Binarios\com_mapobj\0104_mapobj.ncer,__Imagens\com_mapobj\",
                ["0110_mapobj.ncgr"] = @"__Binarios\com_mapobj\0110_mapobj.ncgr,__Binarios\com_mapobj\0111_mapobj.nclr,__Binarios\com_mapobj\0108_mapobj.ncer,__Imagens\com_mapobj\",
                ["0114_mapobj.ncgr"] = @"__Binarios\com_mapobj\0114_mapobj.ncgr,__Binarios\com_mapobj\0115_mapobj.nclr,__Binarios\com_mapobj\0112_mapobj.ncer,__Imagens\com_mapobj\",
                ["0118_mapobj.ncgr"] = @"__Binarios\com_mapobj\0118_mapobj.ncgr,__Binarios\com_mapobj\0119_mapobj.nclr,__Binarios\com_mapobj\0116_mapobj.ncer,__Imagens\com_mapobj\",
                ["0122_mapobj.ncgr"] = @"__Binarios\com_mapobj\0122_mapobj.ncgr,__Binarios\com_mapobj\0123_mapobj.nclr,__Binarios\com_mapobj\0120_mapobj.ncer,__Imagens\com_mapobj\",
                ["0126_mapobj.ncgr"] = @"__Binarios\com_mapobj\0126_mapobj.ncgr,__Binarios\com_mapobj\0127_mapobj.nclr,__Binarios\com_mapobj\0124_mapobj.ncer,__Imagens\com_mapobj\",
                ["0130_mapobj.ncgr"] = @"__Binarios\com_mapobj\0130_mapobj.ncgr,__Binarios\com_mapobj\0131_mapobj.nclr,__Binarios\com_mapobj\0128_mapobj.ncer,__Imagens\com_mapobj\",
                ["0134_mapobj.ncgr"] = @"__Binarios\com_mapobj\0134_mapobj.ncgr,__Binarios\com_mapobj\0135_mapobj.nclr,__Binarios\com_mapobj\0132_mapobj.ncer,__Imagens\com_mapobj\",
                ["0138_mapobj.ncgr"] = @"__Binarios\com_mapobj\0138_mapobj.ncgr,__Binarios\com_mapobj\0139_mapobj.nclr,__Binarios\com_mapobj\0136_mapobj.ncer,__Imagens\com_mapobj\",
                ["0142_mapobj.ncgr"] = @"__Binarios\com_mapobj\0142_mapobj.ncgr,__Binarios\com_mapobj\0143_mapobj.nclr,__Binarios\com_mapobj\0140_mapobj.ncer,__Imagens\com_mapobj\",
                ["0146_mapobj.ncgr"] = @"__Binarios\com_mapobj\0146_mapobj.ncgr,__Binarios\com_mapobj\0147_mapobj.nclr,__Binarios\com_mapobj\0144_mapobj.ncer,__Imagens\com_mapobj\",
                ["0150_mapobj.ncgr"] = @"__Binarios\com_mapobj\0150_mapobj.ncgr,__Binarios\com_mapobj\0151_mapobj.nclr,__Binarios\com_mapobj\0148_mapobj.ncer,__Imagens\com_mapobj\",
                ["0154_mapobj.ncgr"] = @"__Binarios\com_mapobj\0154_mapobj.ncgr,__Binarios\com_mapobj\0155_mapobj.nclr,__Binarios\com_mapobj\0152_mapobj.ncer,__Imagens\com_mapobj\",
                ["0158_mapobj.ncgr"] = @"__Binarios\com_mapobj\0158_mapobj.ncgr,__Binarios\com_mapobj\0159_mapobj.nclr,__Binarios\com_mapobj\0156_mapobj.ncer,__Imagens\com_mapobj\",
                ["0162_mapobj.ncgr"] = @"__Binarios\com_mapobj\0162_mapobj.ncgr,__Binarios\com_mapobj\0163_mapobj.nclr,__Binarios\com_mapobj\0160_mapobj.ncer,__Imagens\com_mapobj\",
                ["0166_mapobj.ncgr"] = @"__Binarios\com_mapobj\0166_mapobj.ncgr,__Binarios\com_mapobj\0167_mapobj.nclr,__Binarios\com_mapobj\0164_mapobj.ncer,__Imagens\com_mapobj\",
                ["0170_mapobj.ncgr"] = @"__Binarios\com_mapobj\0170_mapobj.ncgr,__Binarios\com_mapobj\0171_mapobj.nclr,__Binarios\com_mapobj\0168_mapobj.ncer,__Imagens\com_mapobj\",
                ["0174_mapobj.ncgr"] = @"__Binarios\com_mapobj\0174_mapobj.ncgr,__Binarios\com_mapobj\0175_mapobj.nclr,__Binarios\com_mapobj\0172_mapobj.ncer,__Imagens\com_mapobj\",
                ["0178_mapobj.ncgr"] = @"__Binarios\com_mapobj\0178_mapobj.ncgr,__Binarios\com_mapobj\0179_mapobj.nclr,__Binarios\com_mapobj\0176_mapobj.ncer,__Imagens\com_mapobj\",
                ["0182_mapobj.ncgr"] = @"__Binarios\com_mapobj\0182_mapobj.ncgr,__Binarios\com_mapobj\0183_mapobj.nclr,__Binarios\com_mapobj\0180_mapobj.ncer,__Imagens\com_mapobj\",
                ["0186_mapobj.ncgr"] = @"__Binarios\com_mapobj\0186_mapobj.ncgr,__Binarios\com_mapobj\0187_mapobj.nclr,__Binarios\com_mapobj\0184_mapobj.ncer,__Imagens\com_mapobj\"

            };
        }
    }
}
