//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JacutemAAI2.WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiretorioRomDesmonstada {
            get {
                return ((string)(this["DiretorioRomDesmonstada"]));
            }
            set {
                this["DiretorioRomDesmonstada"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UltimaPastaFolderPicker {
            get {
                return ((string)(this["UltimaPastaFolderPicker"]));
            }
            set {
                this["UltimaPastaFolderPicker"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Binarios")]
        public string PastaBinarios {
            get {
                return ((string)(this["PastaBinarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Binarios\\_InfoBinarios")]
        public string PastaInfoBinarios {
            get {
                return ((string)(this["PastaInfoBinarios"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Imagens")]
        public string PastaImagens {
            get {
                return ((string)(this["PastaImagens"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Imagens\\__Imagens_editadas")]
        public string PastaImagensEditadas {
            get {
                return ((string)(this["PastaImagensEditadas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Textos")]
        public string PastaTextos {
            get {
                return ((string)(this["PastaTextos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Textos\\_Tabelas")]
        public string PastaTabelas {
            get {
                return ((string)(this["PastaTabelas"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Textos\\Scripts_Originais")]
        public string PastaScriptsOriginais {
            get {
                return ((string)(this["PastaScriptsOriginais"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Textos\\Scripts_Traduzidos")]
        public string PastaScriptsTraduzidos {
            get {
                return ((string)(this["PastaScriptsTraduzidos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("__Tools")]
        public string PastaTools {
            get {
                return ((string)(this["PastaTools"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ndstool.exe")]
        public string ToolNdstool {
            get {
                return ((string)(this["ToolNdstool"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("libgcc_s_seh-1.dll")]
        public string ToolNdstoolLibgcc_s_seh_1 {
            get {
                return ((string)(this["ToolNdstoolLibgcc_s_seh_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("libstdc++-6.dll")]
        public string ToolNdstoolLibstdc_6 {
            get {
                return ((string)(this["ToolNdstoolLibstdc_6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("libwinpthread-1.dll")]
        public string ToolNdstoolLibwinpthread_1 {
            get {
                return ((string)(this["ToolNdstoolLibwinpthread_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blz.exe")]
        public string ToolBlz {
            get {
                return ((string)(this["ToolBlz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_infoScripts.txt")]
        public string TextosInfoScript {
            get {
                return ((string)(this["TextosInfoScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aai2.tbl")]
        public string TextosTabelaAAI2 {
            get {
                return ((string)(this["TextosTabelaAAI2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aai2_botoes.tbl")]
        public string TextosTabelaAAI2_Botoes {
            get {
                return ((string)(this["TextosTabelaAAI2_Botoes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aai2_descricoes.tbl")]
        public string TextosTabelaAAI2_Descricoes {
            get {
                return ((string)(this["TextosTabelaAAI2_Descricoes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tabelaTag.tbl")]
        public string TextosTabelaAAI2_TabelaTag {
            get {
                return ((string)(this["TextosTabelaAAI2_TabelaTag"]));
            }
            set {
                this["TextosTabelaAAI2_TabelaTag"] = value;
            }
        }
    }
}
